# Generated by Django 5.1.7 on 2025-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
